GAME_NAME_MAP = {
    "Ace Combat 7: Skies Unknown": "皇牌空战7：未知天空",
    "Against the Storm": "对抗风暴",
    "Age of Empires III: Definitive Edition": "帝国时代 III：决定版",
    "Age of Empires II: Definitive Edition": "帝国时代 II：决定版",
    "Age of Empires IV": "帝国时代 IV",
    "Age of Wonders 4": "奇迹时代4",
    "Age of Wonders: Planetfall": "奇迹时代：坠落星球",
    "Airship: Kingdoms Adrift": "飞艇：王国漂流",
    "Alan Wake 2": "心灵杀手2",
    "Aliens: Fireteam Elite": "异形：精英火力小队",
    "Alone in the Dark": "独自在黑暗中",
    "Amazing Cultivation Simulator": "神奇的养成模拟器",
    "Ancestors Legacy": "祖先的遗产",
    "Ancestors: The Humankind Odyssey": "祖先：人类奥德赛",
    "Angel at Dusk": "黄昏的天使",
    "Anno 1404 – History Edition": "《纪元 1404》- 历史版",
    "Anno 1800": "纪元1800",
    "Another Crab’s Treasure": "另一种螃蟹的宝藏",
    "ANVIL": "砧",
    "Aragami 2": "荒神2",
    "ARK: Survival Evolved": "方舟：生存进化",
    "Armored Core VI Fires of Rubicon": "装甲核心 VI 卢比孔河之火",
    "Assassin’s Creed IV: Black Flag": "刺客信条 IV：黑旗",
    "Assassin’s Creed Mirage": "刺客信条幻影",
    "Assassin’s Creed Odyssey": "刺客信条奥德赛",
    "Assassin’s Creed Origins": "刺客信条起源",
    "Assassin’s Creed Valhalla": "刺客信条瓦尔哈拉",
    "ASTLIBRA Revision": "ASTLIBRA 修订版",
    "Astria Ascending": "阿斯特里亚上升",
    "Astroneer": "太空人",
    "Atelier Lulua: The Scion of Arland": "露露亚工作室：亚兰德的后裔",
    "Atelier Ryza 2: Lost Legends & the Secret Fairy": "莱莎炼金工房 2：失落的传说与秘密妖精",
    "Atelier Ryza 3: Alchemist of the End & the Secret Key": "莱莎的炼金工房3：终结的炼金术士与秘密钥匙",
    "Atelier Ryza: Ever Darkness & the Secret Hideout": "莱莎的炼金工房：常暗与秘密藏身处",
    "Atlas Fallen": "阿特拉斯堕落者",
    "Atomic Heart": "原子心",
    "Avatar: Frontiers of Pandora": "阿凡达：潘多拉边境",
    "Azur Lane: Crosswave": "碧蓝航线：Crosswave",
    "A Plague Tale: Innocence": "瘟疫故事：无罪",
    "Back 4 Blood": "后4血",
    "Baldur’s Gate 3": "博德之门 3",
    "Banishers: Ghosts of New Eden": "放逐者：新伊甸园的幽灵",
    "Banner of the Maid": "女仆的旗帜",
    "Battlefield V": "战地 V",
    "Bellwright": "贝尔赖特",
    "Big Bia": "大比亚",
    "Biomutant": "生物突变体",
    "Black Myth: Wukong": "黑神话：悟空",
    "Blasphemous": "亵渎神灵",
    "Blasphemous 2": "亵渎2",
    "BlazBlue Entropy Effect": "苍翼默示熵效应",
    "Bloodstained: Ritual of the Night": "血污：夜之仪式",
    "Bloody Spell": "血腥咒语",
    "Borderlands 3": "无主之地3",
    "Bravely Default II": "勇敢默认II",
    "Bright Memory": "光明记忆",
    "Bright Memory: Infinite": "光明记忆：无限",
    "Bullet Girls Phantasia": "子弹少女幻想曲",
    "Call Of Duty: Modern Warfare 2 Remastered": "使命召唤：现代战争 2 重制版",
    "Captain Tsubasa: Rise of New Champions": "小翼：新冠军的崛起",
    "Chernobylite": "切尔诺贝利岩",
    "Chinese Parents": "中国家长",
    "Chorus": "合唱",
    "Chrono Ark": "时空方舟",
    "Cities: Skylines II": "城市：天际线 II",
    "Cluckmech Oasis": "克拉克机械绿洲",
    "Code Vein": "代码静脉",
    "Commandos 2 – HD Remaster": "盟军敢死队 2 – 高清重制版",
    "Command & Conquer Remastered Collection": "命令与征服重制版合集",
    "Conan Unconquered": "不败柯南",
    "Contra: Rogue Corps": "魂斗罗：盗贼军团",
    "Control Ultimate Edition": "控制终极版",
    "Core Keeper": "核心守护者",
    "Craftopia": "创世国",
    "Crime Boss: Rockay City": "犯罪头目：洛基市",
    "Crisis Core Final Fantasy VII Reunion": "最终幻想 VII 核心危机重聚",
    "Crown Trick": "皇冠戏法",
    "Crusader Kings III": "十字军之王3",
    "Crying Suns": "哭泣的太阳",
    "Crysis Remastered": "孤岛危机重制版",
    "Cult of the Lamb": "羔羊崇拜",
    "Cuphead": "茶杯头",
    "Curious Expedition 2": "好奇探险队2",
    "Curse of the Dead Gods": "死神的诅咒",
    "Cyberpunk 2077": "赛博朋克2077",
    "Daemon X Machina": "恶魔X机械",
    "Darkest Dungeon II": "黑暗地牢 II",
    "Darkest Dungeon": "黑暗地牢",
    "Darksiders Genesis": "暗黑血统创世记",
    "Dark Souls III": "黑暗之魂3",
    "Dark Souls: Remastered": "黑暗之魂：重制版",
    "Dave The Diver": "潜水员戴夫",
    "Daymare: 1998": "白日噩梦：1998",
    "Days Gone": "日子一去不复返",
    "Dead Cells": "死亡细胞",
    "Dead Island 2": "死亡岛2",
    "Dead or Alive 6": "死或生6",
    "Dead Space Remake": "死亡空间重制版",
    "DEATHLOOP": "死亡循环",
    "Death end re;Quest": "死亡终局：任务",
    "Death end re;Quest 2": "死亡终局：任务2",
    "Death Stranding Director’s Cut": "死亡搁浅导演剪辑版",
    "Death’s Door": "死亡之门",
    "Death’s Gambit: Afterlife": "死亡的策略：来世",
    "Deep Rock Galactic: Survivor": "深岩银河：幸存者",
    "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles": "鬼灭之刃-鬼灭之刃-日神编年史",
    "Desperados III": "亡命之徒 III",
    "Destroy All Humans!": "毁灭全人类！",
    "Devil May Cry 5": "鬼泣5",
    "Devil Slayer – Raksasi": "恶魔杀手——拉克西斯",
    "Devil’s Hunt": "恶魔的狩猎",
    "Dicefolk": "骰子人",
    "Digimon Story Cyber Sleuth: Complete Edition": "数码宝贝物语网络侦探：完全版",
    "Digimon Survive": "数码宝贝生存",
    "DIRT 5": "污垢5",
    "Disciples: Liberation": "弟子：解脱",
    "Disco Elysium": "极乐迪斯科",
    "Disgaea 6 Complete": "魔界战记 6 已完成",
    "Dishonored 2": "耻辱2",
    "Disney Dreamlight Valley": "迪士尼梦光谷",
    "Divinity: Original Sin 2 Definitive Edition": "神界：原罪 2 最终版",
    "Dohna Dohna": "多纳多纳",
    "DOOM Eternal": "毁灭战士永恒",
    "Door Kickers: Action Squad": "破门而入：行动小队",
    "Doraemon Story Of Seasons": "哆啦A梦四季物语",
    "Dragon Ball FighterZ": "龙珠斗士Z",
    "Dragon Ball Xenoverse 2": "龙珠超宇宙2",
    "Dragon Ball Z: Kakarot": "龙珠Z：卡卡罗特",
    "Dragon Quest Builders 2": "勇者斗恶龙 创世者2",
    "DRAGON QUEST XI S: Echoes of an Elusive Age Definitive Edition": "勇者斗恶龙 XI S：难以捉摸的时代的回声 最终版",
    "Dragon Quest X Offline": "勇者斗恶龙 X 离线",
    "Dragon’s Dogma 2": "龙之信条2",
    "Dragon’s Dogma: Dark Arisen": "龙之信条：黑暗崛起",
    "DreadOut 2": "恐惧2",
    "Dream Rivakes": "梦想里瓦克斯",
    "DREDGE": "疏通",
    "Dungeons & Dragons: Dark Alliance": "龙与地下城：黑暗联盟",
    "Dungeons 4": "地下城4",
    "Dying Light 2 Stay Human": "《消逝的光芒 2》保持人性",
    "Dying Light: Enhanced Edition": "《消逝的光芒：增强版》",
    "Dynasty Warriors 8: Xtreme Legends Complete Edition": "三国无双8：极限传奇完整版",
    "Dynasty Warriors 9: Empires": "三国无双9：帝国",
    "Dyson Sphere Program": "戴森球计划",
    "Earth Defense Force 5": "地球防卫军5",
    "EARTH DEFENSE FORCE 6": "地球防卫军6",
    "Eastern Exorcist": "东方大法师",
    "Eastward": "向东",
    "eFootball PES 2020": "电子足球 PES 2020",
    "eFootball PES 2021": "电子足球 PES 2021",
    "Eiyuden Chronicle: Hundred Heroes": "永游传编年史：百英雄",
    "Elden Ring Shadow of the Erdtree": "埃尔登之戒 大树之影",
    "Endzone – A World Apart": "Endzone – 一个截然不同的世界",
    "Enshrouded": "笼罩着",
    "Esports Godfather": "电竞教父",
    "Everspace": "永恒空间",
    "Everspace 2": "永恒空间2",
    "Evil West": "邪恶的西部",
    "Fabledom": "寓言王国",
    "Fairy Tail": "妖精的尾巴",
    "Fallout 4": "辐射4",
    "Far Cry 6": "孤岛惊魂6",
    "Fatal Frame / Project Zero: Mask of the Lunar Eclipse": "致命框架 / 零号计划：月食面具",
    "Fatal Frame/Project Zero: Maiden of Black Water": "致命框架/零号计划：黑水少女",
    "Fate Seeker II": "命运探索者 II",
    "Fate Seeker": "命运探索者",
    "Fate/Samurai Remnant": "命运/武士遗迹",
    "Final Fantasy III (Pixel Remaster)": "最终幻想 III（像素重制版）",
    "Final Fantasy II (Pixel Remaster)": "最终幻想 II（像素重制版）",
    "Final Fantasy IV (Pixel Remaster)": "最终幻想 IV（像素重制版）",
    "Final Fantasy VIII Remastered": "最终幻想 VIII 重制版",
    "Final Fantasy VII Remake Intergrade": "最终幻想 VII 重制版 Intergrade",
    "Final Fantasy VI (Pixel Remaster)": "最终幻想 VI（像素重制版）",
    "Final Fantasy V (Pixel Remaster)": "最终幻想 V（像素重制版）",
    "Final Fantasy (Pixel Remaster)": "最终幻想（像素重制版）",
    "Flintlock: The Siege of Dawn": "燧发枪：黎明之围",
    "Forever Skies": "永远的天空",
    "From Jianghu": "来自江湖",
    "Frostpunk": "霜朋克",
    "F.I.S.T.: Forged In Shadow Torch": "F.I.S.T.：暗影火炬锻造",
    "F1 Manager 2023": "F1 经理 2023",
    "F1 Manager 2024": "F1 经理 2024",
    "F1 24": "F1 24",
    "Galacticare": "银河战士",
    "Galactic Civilizations IV: Supernova": "银河文明 IV：超新星",
    "Gas Station Simulator": "加油站模拟器",
    "Gears Tactics": "齿轮战术",
    "Gears 5": "齿轮5",
    "Generation Zero": "零世代",
    "Ghostrunner": "幽灵行者",
    "Ghostrunner 2": "幽灵行者2",
    "Ghostwire: Tokyo": "幽灵线：东京",
    "Ghost of Tsushima": "对马岛之魂",
    "Godfall": "神陨",
    "God Eater 3": "噬神者3",
    "God of War": "战神",
    "Going Medieval": "走向中世纪",
    "Granblue Fantasy Versus: Rising": "碧蓝幻想对战：崛起",
    "Granblue Fantasy: Relink": "碧蓝幻想：重新链接",
    "Granblue Fantasy: Versus": "碧蓝幻想：对战",
    "Grand Theft Auto III: The Definitive Edition": "侠盗猎车手 III：决定版",
    "Grand Theft Auto V": "侠盗猎车手 V",
    "Grand Theft Auto: San Andreas The Definitive Edition": "侠盗猎车手：圣安地列斯 最终版",
    "Grand Theft Auto: Vice City The Definitive Edition": "侠盗猎车手：罪恶都市决定版",
    "Graveyard Keeper": "墓地守护者",
    "GreedFall": "贪婪之秋",
    "Greedland": "格里德兰",
    "Green Hell": "绿色地狱",
    "Griftlands": "格里夫特兰",
    "GRIME": "污垢",
    "Grounded": "接地",
    "GuLong": "古龙",
    "Gunfire Reborn": "枪火重生",
    "Hades II": "哈迪斯二世",
    "Hades": "哈迪斯",
    "Half-Life: Alyx": "半衰期：爱莉克斯",
    "Halo Infinite (Campaign)": "光环：无限（战役）",
    "Halo: The Master Chief Collection (Halo 2: Anniversary)": "光环：士官长合集（光环 2：周年纪念版）",
    "Halo: The Master Chief Collection (Halo 3)": "光环：士官长合集（光环 3）",
    "Halo: The Master Chief Collection (Halo 3: ODST)": "光环：士官长合集（光环 3：ODST）",
    "Halo: The Master Chief Collection (Halo 4)": "光环：士官长合集（光环 4）",
    "Halo: The Master Chief Collection (Halo: CE Anniversary)": "光环：士官长合集（光环：CE 周年纪念版）",
    "Halo: The Master Chief Collection (Halo: Reach)": "光环：士官长合集（光环：致远星）",
    "Harvestella": "哈韦斯特拉",
    "Haydee 2": "海蒂 2",
    "Hearts of Iron IV": "钢铁雄心 IV",
    "Heroes of the Three Kingdoms 8": "三国英雄8",
    "Hero’s Adventure": "英雄的冒险",
    "HITMAN 2": "杀手2",
    "HITMAN 3": "杀手3",
    "Hobo: Tough Life": "流浪汉：艰难的生活",
    "Hogwarts Legacy": "霍格沃茨的遗产",
    "Hollow Knight": "空洞骑士",
    "Homeworld 3": "家园3",
    "Home Behind 2": "回家后2",
    "Horizon Forbidden West Complete Edition": "地平线 禁断西部 完整版",
    "Horizon Zero Dawn Complete Edition": "地平线零之曙光完整版",
    "HOT WHEELS UNLEASHED": "风火轮已释放",
    "HOT WHEELS UNLEASHED 2 Turbocharged": "风火轮释放 2 涡轮增压",
    "Humankind": "人类",
    "Icarus": "伊卡洛斯",
    "Immortals Fenyx Rising": "渡神纪芬尼斯崛起",
    "Immortal Life": "不朽的生命",
    "Indivisible": "不可分割",
    "Industries of Titan": "泰坦工业",
    "Infection Free Zone": "无感染区",
    "Inscryption": "密码术",
    "Iratus: Lord of the Dead": "伊拉图斯：亡灵之主",
    "Iron Harvest": "铁丰收",
    "Is It Wrong to Try to Pick Up Girls in a Dungeon? Infinite Combate": "尝试在地牢里搭讪有错吗？",
    "Jagged Alliance 3": "铁血联盟3",
    "Jianghu Chronicles": "江湖纪事",
    "JoJo’s Bizarre Adventure: All-Star Battle R": "JoJo的奇妙冒险：全明星之战R",
    "Judgment": "判断",
    "JUMP FORCE": "跳跃力",
    "Jurassic World Evolution": "侏罗纪世界：进化",
    "Jurassic World Evolution 2": "侏罗纪世界：进化2",
    "Kena: Bridge of Spirits": "凯纳：精神之桥",
    "Kingdoms of Amalur: Re-Reckoning": "阿玛拉王国：重新清算",
    "Kingdoms Reborn": "王国重生",
    "Kingdom Come: Deliverance": "天国降临：拯救",
    "Kingdom Hearts Birth by Sleep Final Mix": "王国之心 梦中降生 最终混音",
    "Kingdom Hearts Dream Drop Distance HD": "王国之心 梦境掉落距离 HD",
    "Kingdom Hearts Final Mix": "王国之心最终混音",
    "Kingdom Hearts III": "王国之心3",
    "Kingdom Hearts II Final Mix": "王国之心 II 最终混音",
    "Kingdom Hearts Re: Chain of Memories": "王国之心Re：记忆之链",
    "Kingdom Hearts 0.2: Birth by Sleep – A Fragmentary Passage": "王国之心 0.2：梦中降生——一段片段",
    "Kingdom Rush Vengeance – Tower Defense": "王国保卫战：复仇 - 塔防",
    "King’s Bounty II": "国王的恩赐 II",
    "Kunitsu-Gami: Path of the Goddess": "国津神：女神之路",
    "Last Epoch": "最后纪元",
    "Legend of Mana": "玛娜传奇",
    "Legend of Mortal": "凡人传奇",
    "Library Of Ruina": "瑞纳图书馆",
    "Lies of P": "P的谎言",
    "Like a Dragon Gaiden: The Man Who Erased His Name": "如同龙外传：抹去名字的男人",
    "Like a Dragon: Infinite Wealth": "像龙一样：无限的财富",
    "Like a Dragon: Ishin!": "像龙一样：伊辛！",
    "Little Witch Nobeta": "小魔女诺贝塔",
    "Loop Hero": "循环英雄",
    "Lords of the Fallen": "堕落者领主",
    "Lost Judgment": "失去判断力",
    "Mafia III: Definitive Edition": "四海兄弟 III：决定版",
    "Mafia II: Definitive Edition": "四海兄弟 II：最终版",
    "Mafia: Definitive Edition": "四海兄弟：最终版",
    "Magicraft": "魔法工艺",
    "Maneater": "食人者",
    "Manor Lords": "庄园领主",
    "Marvel’s Avengers": "漫威的复仇者联盟",
    "Marvel’s Guardians of the Galaxy": "漫威的银河护卫队",
    "Marvel’s Midnight Suns": "漫威的午夜太阳",
    "Marvel’s Spider-Man Remastered": "漫威蜘蛛侠重制版",
    "Marvel’s Spider-Man: Miles Morales": "漫威蜘蛛侠：迈尔斯·莫拉莱斯",
    "Mass Effect Legendary Edition (Mass Effect 1)": "质量效应传奇版（质量效应1）",
    "Mass Effect Legendary Edition (Mass Effect 2)": "质量效应传奇版（质量效应2）",
    "Mass Effect Legendary Edition (Mass Effect 3)": "质量效应传奇版（质量效应3）",
    "MechWarrior 5: Mercenaries": "机甲战士 5：雇佣兵",
    "Medieval Dynasty": "中世纪王朝",
    "Mega Man Battle Network Legacy Collection Vol. 1": "洛克人战斗网络遗产合集卷。 ",
    "Mega Man Battle Network Legacy Collection Vol. 2": "洛克人战斗网络遗产合集卷。 ",
    "Mega Man X Legacy Collection": "洛克人 X 遗产系列",
    "Mega Man X Legacy Collection 2": "洛克人 X 遗产系列 2",
    "Men of War II": "战争之人2",
    "Metal Gear Solid V: The Phantom Pain": "合金装备 V：幻痛",
    "Metro Exodus": "地铁：离去",
    "Millennia": "千年",
    "Minecraft Dungeons": "我的世界地下城",
    "MISTOVER": "迷雾",
    "Mi Chang Sheng": "觅长生",
    "Monkey King: Hero is Back": "大圣归来",
    "Monster Hunter Rise": "怪物猎人崛起",
    "Monster Hunter Stories 2: Wings of Ruin": "怪物猎人物语2：毁灭之翼",
    "Monster Hunter World: Iceborne": "怪物猎人世界：冰原",
    "Monster Train": "怪物火车",
    "Mortal Kombat 1": "真人快打1",
    "Mortal Kombat 11": "真人快打11",
    "Mortal Shell": "凡人躯壳",
    "Mount & Blade II: Bannerlord": "骑马与砍杀 II：领主",
    "Mr. Prepper": "末日准备者先生",
    "Myth of Empires": "帝国神话",
    "My Friend Pedro": "我的朋友佩德罗",
    "My Hero One’s Justice 2": "我的英雄学院唯我正义2",
    "My Time at Sandrock": "我在沙岩的时光",
    "Narcos: Rise of the Cartels": "毒枭：贩毒集团的崛起",
    "NBA 2K20": "NBA 2K20",
    "NBA 2K21": "NBA 2K21",
    "NBA 2K22": "NBA 2K22",
    "NBA 2K23": "NBA 2K23",
    "Necromunda: Hired Gun": "涅克洛蒙达：雇佣枪",
    "Need for Speed Heat": "极品飞车热度",
    "Neon Abyss": "霓虹深渊",
    "New Cycle": "新周期",
    "Next Jianghu II": "下一篇 江湖II",
    "NieR Replicant": "尼尔复制人",
    "NieR: Automata": "尼尔：机械纪元",
    "Nine Sols": "九索尔",
    "Ninja Gaiden: Master Collection (Ninja Gaiden Sigma 2)": "忍者龙剑传：大师合集（忍者龙剑传西格玛2）",
    "Ninja Gaiden: Master Collection (Ninja Gaiden Sigma)": "忍者龙剑传：大师合集（忍者龙剑传西格玛）",
    "Ninja Gaiden: Master Collection (Ninja Gaiden 3: Razor’s Edge)": "忍者龙剑传：大师合集（忍者龙剑传 3：剃刀边缘）",
    "Nioh 2 The Complete Edition": "仁王 2 完全版",
    "Nioh: Complete Edition": "仁王：完全版",
    "Ni no Kuni: Wrath of the White Witch Remastered": "二之国：白女巫之怒重制版",
    "Nobody – The Turnaround": "无人——逆转",
    "NOBUNAGA’S AMBITION: Awakening": "信长的野心：觉醒",
    "Noita": "诺伊塔",
    "Norland": "诺兰德",
    "No Man’s Sky": "无人深空",
    "No Rest for the Wicked": "恶人不得安息",
    "Oblivion Override": "遗忘覆盖",
    "Octopath Traveler II": "八方旅人II",
    "Octopath Traveler": "八方旅人",
    "Office Life": "办公生活",
    "One Piece Odyssey": "海贼王奥德赛",
    "One Piece: Pirate Warriors 4": "海贼王：海贼无双4",
    "One Punch Man: A Hero Nobody Knows": "一拳超人：无人知晓的英雄",
    "ONINAKI": "鬼崎",
    "Orcs Must Die! 3": "兽人必须死！ ",
    "Ori and the Will of the Wisps": "奥日与萤火意志",
    "Outer Wilds": "星际拓荒",
    "Outpost: Infinity Siege": "前哨站：无限围攻",
    "Outriders": "先驱者",
    "Outward Definitive Edition": "外传最终版",
    "Outward": "向外",
    "Pacific Drive": "太平洋大道",
    "Palworld": "友世界",
    "Pathfinder: Kingmaker": "探路者：拥王者",
    "Pathfinder: Wrath of the Righteous": "探路者：正义之怒",
    "Path Of Wuxia": "武侠之路",
    "PC Building Simulator": "电脑组装模拟器",
    "PC Building Simulator 2": "电脑组装模拟器 2",
    "Persona 3 Portable": "女神异闻录 3 便携版",
    "Persona 3 Reload": "女神异闻录 3 重装上阵",
    "Persona 4 Golden": "女神异闻录 4 黄金版",
    "Persona 5 Royal": "女神异闻录 5 皇家",
    "Persona 5 Strikers": "女神异闻录5前锋",
    "Phoenix Point": "凤凰点",
    "Plague Inc: Evolved": "瘟疫公司：进化",
    "Planet Zoo": "动物园之星",
    "Potion Craft: Alchemist Simulator": "药水工艺：炼金术士模拟器",
    "PowerWash Simulator": "PowerWash 模拟器",
    "Prey": "猎物",
    "Project Wingman": "僚机计划",
    "Psychonauts 2": "心灵航海者2",
    "Rabbit and Steel": "兔子与钢铁",
    "Raft": "筏",
    "Rage 2": "狂怒2",
    "Rebel Inc: Escalation": "叛军公司：升级",
    "Red Dead Redemption 2": "荒野大镖客：救赎 2",
    "Red Solstice 2: Survivors": "赤日至2：幸存者",
    "Remnant II": "遗迹II",
    "Remnant: From the Ashes": "遗迹：灰烬中",
    "Resident Evil Village": "生化危机村庄",
    "Resident Evil 2": "生化危机2",
    "Resident Evil 3": "生化危机3",
    "Resident Evil 4": "生化危机4",
    "Resident Evil 7: Biohazard": "生化危机 7：生化危机",
    "Returnal": "返回",
    "Risk of Rain 2": "下雨的危险2",
    "Robin Hood – Sherwood Builders": "罗宾汉 – 舍伍德建筑商",
    "RoboCop: Rogue City": "机械战警：侠盗城",
    "Romance of the Three Kingdoms XIV": "三国演义XIV",
    "Ruined King: A League of Legends Story": "毁灭之王：英雄联盟故事",
    "Rune Factory 3 Special": "符文工厂 3 特别版",
    "Rune Factory 4 Special": "符文工厂 4 特别版",
    "Rune Factory 5": "符文工厂 5",
    "SaGa Frontier Remastered": "沙加边境重制版",
    "Saints Row": "黑道圣徒",
    "Saints Row: The Third Remastered": "黑道圣徒：第三重制版",
    "Sakuna: Of Rice and Ruin": "萨库纳：稻米与废墟",
    "Salt and Sanctuary": "盐与庇护所",
    "Samurai Warriors 4 DX": "武士无双4 DX",
    "Samurai Warriors 5": "武士无双5",
    "Sands of Salzaar": "萨尔扎尔之沙",
    "SAND LAND": "沙地",
    "Satisfactory": "满意",
    "Scarlet Nexus": "猩红纽带",
    "SD Gundam Battle Alliance": "SD高达战斗联盟",
    "SD Gundam G Generation Cross Rays": "SD高达G世代 火线纵横",
    "Secrets of Grindea": "格林迪亚的秘密",
    "Sekiro: Shadows Die Twice": "只狼：影逝二度",
    "Sengoku Dynasty": "战国王朝",
    "Serious Sam 4": "严肃的萨姆4",
    "Shenmue 3": "莎木3",
    "Sherlock Holmes Chapter One": "夏洛克·福尔摩斯第一章",
    "She Will Punish Them": "她会惩罚他们",
    "Shin Megami Tensei III Nocturne HD Remaster": "真女神转生 III 夜曲 HD 重制版",
    "Shin Megami Tensei V: Vengeance": "真女神转生V：复仇",
    "Sid Meier’s Civilization VI": "席德梅尔的文明VI",
    "Sifu": "师傅",
    "Skul: The Hero Slayer": "斯库尔：英雄杀手",
    "Sleeping Dogs: Definitive Edition": "沉睡的狗：最终版",
    "Sniper Ghost Warrior Contracts": "狙击手幽灵战士契约",
    "Sniper Ghost Warrior Contracts 2": "狙击手幽灵战士契约2",
    "SnowRunner": "雪行者",
    "Soda Dungeon 2": "苏打地牢2",
    "Songs of Conquest": "征服之歌",
    "Sons Of The Forest": "森林之子",
    "Sons of Valhalla": "瓦尔哈拉之子",
    "Soulcalibur VI": "剑魂VI",
    "Soulmask": "灵魂面具",
    "Soulstone Survivors": "灵魂石幸存者",
    "Soul Hackers 2": "灵魂黑客2",
    "SpellForce 3: Fallen God": "咒语力量 3：堕落之神",
    "SpellForce 3: Soul Harvest": "咒语力量 3：灵魂收割",
    "Spelunky 2": "洞穴探险2",
    "Spiritfarer": "灵魂使者",
    "SpongeBob SquarePants: Battle for Bikini Bottom – Rehydrated": "海绵宝宝：比基尼泳裤之战 – 补水",
    "Spyro Reignited Trilogy": "小龙斯派罗：重燃三部曲",
    "Stardew Valley": "星露谷物语",
    "Starfield": "星空",
    "Star Ocean: The Second Story R": "星之海洋：第二个故事R",
    "Star Wars Jedi: Fallen Order": "星球大战绝地：陨落的武士团",
    "Star Wars: Squadrons": "星球大战：中队",
    "State of Decay 2: Juggernaut Edition": "腐烂国度 2：主宰版",
    "Stellaris": "群星",
    "Stoneshard": "碎石",
    "Story of Seasons: A Wonderful Life": "季节的故事：美好的生活",
    "Story of Seasons: Friends of Mineral Town": "季节的故事：矿产镇之友",
    "Story of Seasons: Pioneers of Olive Town": "季节的故事：橄榄镇的先驱",
    "Stranger of Paradise: Final Fantasy Origin": "天堂陌生人：最终幻想起源",
    "Stray": "流浪者",
    "Streets of Rage 4": "愤怒之街4",
    "Street Fighter V: Champion Edition": "街头霸王 V：冠军版",
    "Stronghold: Definitive Edition": "要塞：最终版",
    "Stronghold: Warlords": "要塞：军阀",
    "Subnautica": "深海迷航",
    "Subnautica: Below Zero": "深海迷航：零以下",
    "Subverse": "颠覆",
    "Succubus": "魅魔",
    "Sunkenland": "沉没之地",
    "Supermarket Simulator": "超市模拟器",
    "Super Monkey Ball: Banana Blitz HD": "超级猴子球：香蕉闪电战 HD",
    "Super Robot Wars V": "超级机器人大战V",
    "Super Robot Wars X": "超级机器人大战X",
    "Super Robot Wars 30": "超级机器人大战30",
    "Swords & Souls: Neverseen": "剑与灵魂：从未见过",
    "Sword and Fairy Inn 2": "剑仙客栈2",
    "Sword and Fairy 7": "剑与仙女7",
    "Sword Art Online: Alicization Lycoris": "刀剑神域：Alicization 石蒜",
    "Taboo Trial": "禁忌审判",
    "Taiko Risshiden V DX": "太鼓立志电 V DX",
    "Tainted Grail: Conquest": "被污染的圣杯：征服",
    "Tales of Arise": "崛起的故事",
    "Tale of Immortal": "不朽的故事",
    "Team Sonic Racing": "索尼克赛车队",
    "Terminator: Dark Fate – Defiance": "终结者：黑暗命运——反抗",
    "Terminator: Resistance": "终结者：抵抗",
    "Terraria": "泰拉瑞亚",
    "TEVI": "特维",
    "They Are Billions": "他们有数十亿",
    "The Ascent": "上升",
    "The Callisto Protocol": "木卫四协议",
    "The DioField Chronicle": "DioField 纪事",
    "The Elder Scrolls V: Skyrim Special Edition": "上古卷轴 V：天际特别版",
    "The Evil Within": "内心的邪恶",
    "THE iDOLM@STER: Starlit Season": "偶像大师：星光季节",
    "The Last of Us Part I": "最后生还者第一部分",
    "The Last Spell": "最后的咒语",
    "The Last Stand: Aftermath": "最后的立场：后果",
    "The Legend of Heroes: Kuro no Kiseki II -CRIMSON SiN-": "英雄传说 黑之轨迹II -CRIMSON SiN-",
    "The Legend of Heroes: Trails into Reverie": "英雄传说：遐想之路",
    "The Legend of Heroes: Trails of Cold Steel III": "英雄传说：闪之轨迹3",
    "The Legend of Heroes: Trails of Cold Steel IV": "英雄传说：闪之轨迹IV",
    "The Legend of Heroes: Trails through Daybreak": "英雄传说：黎明之路",
    "The Lost Village": "失落的村庄",
    "The Outer Worlds": "外部世界",
    "The Outer Worlds: Spacer’s Choice Edition": "《天外世界：太空人的选择版》",
    "The Riftbreaker": "裂痕者",
    "The Sinking City": "沉没之城",
    "The Surge 2": "浪潮2",
    "The Survivalists": "生存主义者",
    "The Thaumaturge": "奇术师",
    "The Walking Dead: Saints & Sinners": "行尸走肉：圣徒与罪人",
    "The Wind Road": "风路",
    "The Witcher 3: Wild Hunt": "巫师 3：狂猎",
    "This War of Mine": "这是我的战争",
    "Three Kingdoms Zhao Yun": "三国志赵云",
    "Thriving City: Song": "繁荣的城市：歌曲",
    "Thunder Tier One": "雷霆一级",
    "Titanfall 2": "泰坦陨落2",
    "Tokyo Ghoul: re Call to Exist": "东京食尸鬼：重新召唤存在",
    "Tomb Raider": "古墓丽影",
    "Tormented Souls": "受折磨的灵魂",
    "Total War Saga: Troy": "全面战争传奇：特洛伊",
    "Total War: PHARAOH DYNASTIES": "全面战争：法老王朝",
    "Total War: ROME REMASTERED": "全面战争：罗马重制版",
    "Total War: THREE KINGDOMS": "全面战争：三个王国",
    "Total War: Warhammer III": "全面战争：战锤 III",
    "Total War: Warhammer II": "全面战争：战锤 II",
    "Touhou Hero of Ice Fairy": "东方冰之英雄英雄",
    "Touhou Mystia’s Izakaya": "东方Mystia的居酒屋",
    "Transport Fever 2": "运输狂热2",
    "Trials of Mana": "玛娜的试炼",
    "Tribes of Midgard": "米德加德部落",
    "Trine 4: The Nightmare Prince": "《三位一体 4：噩梦王子》",
    "Trine 5: A Clockwork Conspiracy": "《三位一体 5：发条阴谋》",
    "Tropico 6": "海岛大亨 6",
    "Two Point Campus": "两点校园",
    "Two Point Hospital": "两点医院",
    "Uncharted Waters IV HD Version": "神秘海域 IV 高清版",
    "UNCHARTED: Legacy of Thieves Collection": "《神秘海域：盗贼的遗产》合集",
    "Until We Die": "直到我们死去",
    "Valheim": "瓦尔海姆",
    "Vampire’s Fall: Origins": "吸血鬼的堕落：起源",
    "Victoria 3": "维多利亚3号",
    "V Rising": "V 崛起",
    "Wandering Sword": "流浪剑",
    "Wargroove": "战纹",
    "Warhammer 40": "战锤40",
    "000: Chaos Gate – Daemonhunters": "000：混沌之门 – 恶魔猎手",
    "000: Rogue Trader": "000：流氓商人",
    "Warhammer: Chaosbane": "战锤：混沌祸根",
    "Warm Snow": "暖雪",
    "WARNO": "沃诺",
    "WARRIORS OROCHI 3 Ultimate Definitive Edition": "《无双大蛇 3》终极最终版",
    "Warriors Orochi 4: Ultimate": "无双大蛇4：终极版",
    "Wartales": "沃塔莱斯",
    "War Hospital": "战地医院",
    "Wasteland 3": "荒原3",
    "Watch Dogs 2": "看门狗2",
    "Watch Dogs: Legion": "看门狗：军团",
    "Welcome to ParadiZe": "欢迎来到天堂",
    "Werewolf: The Apocalypse – Earthblood": "狼人：天启 - 大地之血",
    "Wild Hearts": "狂野之心",
    "WitchSpring R": "女巫之泉R",
    "Wolcen: Lords of Mayhem": "沃尔森：混乱之王",
    "Wolfenstein: Youngblood": "德军总部：新血脉",
    "World War Z/World War Z: Aftermath": "僵尸世界大战/僵尸世界大战：后果",
    "Wo Long: Fallen Dynasty": "卧龙：没落王朝",
    "Wreckfest": "沉船节",
    "WWE 2K20": "《WWE 2K20》",
    "XCOM 2": "幽浮2",
    "XCOM: Chimera Squad": "XCOM：奇美拉小队",
    "Xuan-Yuan Sword VII": "轩辕剑七",
    "Yakuza Kiwami 2": "如龙极酷2",
    "Yakuza 3 Remastered": "如龙 3 重制版",
    "Yakuza 4 Remastered": "如龙 4 重制版",
    "Yakuza 5 Remastered": "如龙 5 重制版",
    "Yakuza 6: The Song of Life": "如龙 6：生命之歌",
    "Yakuza: Like a Dragon": "如龙：像龙一样",
    "Yaoling: Mythical Journey": "妖灵：神话之旅",
    "Yes": "是的",
    "Your Grace": "陛下",
    "Ys IX: Monstrum Nox": "伊苏 IX：怪物诺克斯",
    "Ys VIII: Lacrimosa of Dana": "伊苏VIII：达纳的泪水",
    "Ys X: Nordics": "伊苏X：北欧",
    "Ys: Memories of Celceta": "伊苏：塞尔塞塔的回忆",
    "Zhenxie": "真邪",
    "Zombie Army 4: Dead War": "僵尸军团4：死亡之战",
    "60 Parsecs!": "60 秒差距！",
    "7 Days to Die": "7日杀",
    "Elden Ring Shadow of the Erdt": "埃尔登之戒 埃尔特之影",
    "Sekiro: Shadows Die Twic": "《只狼：影逝二度》",
    "Monster Hunter World: Icebo": "怪物猎人世界：冰波",
    "Flintlock: The Siege of Daw": "燧发枪：道之围攻",
}
